name: Simple CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      # Add default values for required environment variables
      MONGODB_URI: ${{ secrets.MONGODB_URI || 'mongodb://localhost:27017/waitlist_db' }}
      EMAIL_USER: ${{ secrets.EMAIL_USER || 'test@example.com' }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS || 'password' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install
          # Check for peer dependency issues
          npm ls || true

      - name: Check for TypeScript errors
        run: |
          npx tsc --noEmit || echo "TypeScript check failed but continuing build"

      - name: Run ESLint with auto-fix
        run: |
          npm run lint -- --fix || echo "Linting failed but continuing build"

      - name: Build Next.js app
        run: |
          # Remove next.config.ts if it exists to avoid conflicts
          [ -f next.config.ts ] && rm next.config.ts || echo "No next.config.ts file found"
          npm run build
